[package]
name = "async-function-pointer-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.35.1", features = ["rt", "rt-multi-thread", "macros"] }
futures = "0.3.30"
